#!/bin/bash
# Linux Emergency Response Collection Script
# Generated by Emergency Response Platform
# ==========================================

OUTPUT_DIR="$(cd "$(dirname "$0")" && pwd)"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="$OUTPUT_DIR/emergency_collection_${TIMESTAMP}.json"

echo "========================================"
echo "  Emergency Response Collection Script"
echo "  Generated by Emergency Response Platform"
echo "========================================"
echo ""

echo "[1/8] Collecting System Information..."
HOSTNAME=$(hostname)
OS_NAME=$(cat /etc/os-release 2>/dev/null | grep "^PRETTY_NAME" | cut -d'"' -f2)
OS_VERSION=$(uname -r)
OS_ARCH=$(uname -m)
UPTIME=$(uptime -p 2>/dev/null | sed 's/up //')
CURRENT_USER=$(whoami)
CPU_MODEL=$(grep "model name" /proc/cpuinfo 2>/dev/null | head -1 | cut -d':' -f2 | xargs)
CPU_CORES=$(nproc 2>/dev/null)
TOTAL_MEM=$(free -h 2>/dev/null | awk '/^Mem:/{print $2}')

cat > "$OUTPUT_FILE" << EOFJSON
{
  "system_info": {
    "hostname": "$HOSTNAME",
    "os_name": "$OS_NAME",
    "os_version": "$OS_VERSION",
    "os_arch": "$OS_ARCH",
    "kernel_version": "$OS_VERSION",
    "uptime": "$UPTIME",
    "current_user": "$CURRENT_USER",
    "cpu_model": "$CPU_MODEL",
    "cpu_cores": $CPU_CORES,
    "total_memory": "$TOTAL_MEM",
    "disk_info": [
EOFJSON

df -h 2>/dev/null | grep -vE '^Filesystem|tmpfs|devtmpfs' | while read -r line; do
    MOUNT=$(echo "$line" | awk '{print $6}')
    TOTAL=$(echo "$line" | awk '{print $2}')
    USED=$(echo "$line" | awk '{print $3}')
    AVAIL=$(echo "$line" | awk '{print $4}')
    echo "      {\"mount_point\": \"$MOUNT\", \"total\": \"$TOTAL\", \"used\": \"$USED\", \"available\": \"$AVAIL\"}," >> "$OUTPUT_FILE"
done

sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
    ]
  },
  "users": [
EOFJSON

echo "[2/8] Collecting User Accounts..."
while IFS=: read -r username _ uid gid _ home shell; do
    if [ "$uid" -ge 1000 ] 2>/dev/null || [ "$username" = "root" ]; then
        GROUP=$(id -gn "$username" 2>/dev/null || echo "")
        LAST_LOGIN=$(lastlog -u "$username" 2>/dev/null | tail -1 | awk '{print $NF}')
        IS_ADMIN="false"
        if [ "$username" = "root" ]; then IS_ADMIN="true"; fi
        if id -nG "$username" 2>/dev/null | grep -qw "sudo"; then IS_ADMIN="true"; fi
        echo "    {\"username\": \"$username\", \"uid\": \"$uid\", \"group\": \"$GROUP\", \"home_dir\": \"$home\", \"shell\": \"$shell\", \"last_login\": \"$LAST_LOGIN\", \"is_admin\": $IS_ADMIN}," >> "$OUTPUT_FILE"
    fi
done < /etc/passwd
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "processes": [
EOFJSON

echo "[3/8] Collecting Process List..."
ps aux --no-headers 2>/dev/null | while read -r user pid cpu mem _ _ _ _ _ _ cmd; do
    echo "    {\"pid\": $pid, \"ppid\": 0, \"name\": \"$(basename "$cmd" | cut -d' ' -f1)\", \"user\": \"$user\", \"cpu\": \"$cpu\", \"memory\": \"$mem\", \"start_time\": \"\", \"cmd_line\": \"$(echo "$cmd" | sed 's/"/\\"/g')\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "network_conns": [
EOFJSON

echo "[4/8] Collecting Network Connections..."
ss -tunap 2>/dev/null | tail -n +2 | while read -r proto recv send local remote state rest; do
    LOCAL_ADDR=$(echo "$local" | sed 's/:/ /g' | awk '{print $1}')
    LOCAL_PORT=$(echo "$local" | sed 's/:/ /g' | awk '{print $2}')
    REMOTE_ADDR=$(echo "$remote" | sed 's/:/ /g' | awk '{print $1}')
    REMOTE_PORT=$(echo "$remote" | sed 's/:/ /g' | awk '{print $2}')
    PID=$(echo "$rest" | grep -oP 'pid=\K[0-9]+' || echo "0")
    PROC_NAME=$(echo "$rest" | grep -oP 'users:\(\("\K[^"]+' || echo "")
    echo "    {\"proto\": \"$proto\", \"local_addr\": \"$LOCAL_ADDR\", \"local_port\": \"$LOCAL_PORT\", \"remote_addr\": \"$REMOTE_ADDR\", \"remote_port\": \"$REMOTE_PORT\", \"state\": \"$state\", \"pid\": $PID, \"proc_name\": \"$PROC_NAME\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "services": [
EOFJSON

echo "[5/8] Collecting Services..."
if command -v systemctl &>/dev/null; then
    systemctl list-units --type=service --all --no-pager 2>/dev/null | grep "\.service" | while read -r unit load active sub desc; do
        NAME=$(echo "$unit" | sed 's/\.service//')
        echo "    {\"name\": \"$NAME\", \"display\": \"$desc\", \"status\": \"$active\", \"start_type\": \"$sub\"}," >> "$OUTPUT_FILE"
    done
fi
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "startup_items": [
EOFJSON

echo "[6/8] Collecting Startup Items..."
for f in /etc/rc.local /etc/init.d/* /etc/systemd/system/*.service; do
    if [ -f "$f" ]; then
        BASENAME=$(basename "$f")
        echo "    {\"name\": \"$BASENAME\", \"command\": \"$f\", \"location\": \"$(dirname "$f")\", \"user\": \"root\"}," >> "$OUTPUT_FILE"
    fi
done 2>/dev/null
crontab -l 2>/dev/null | grep -v "^#" | while read -r line; do
    [ -z "$line" ] && continue
    echo "    {\"name\": \"cron-$(echo "$line" | md5sum | cut -c1-8)\", \"command\": \"$line\", \"location\": \"crontab\", \"user\": \"$CURRENT_USER\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "scheduled_tasks": [
EOFJSON

echo "[7/8] Collecting Scheduled Tasks..."
crontab -l 2>/dev/null | grep -v "^#" | while read -r line; do
    [ -z "$line" ] && continue
    SCHEDULE=$(echo "$line" | awk '{print $1" "$2" "$3" "$4" "$5}')
    CMD=$(echo "$line" | awk '{for(i=6;i<=NF;i++) printf "%s ", $i; print ""}')
    echo "    {\"name\": \"cron-task\", \"command\": \"$CMD\", \"schedule\": \"$SCHEDULE\", \"user\": \"$CURRENT_USER\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "security_logs": [
EOFJSON

echo "[8/8] Collecting Security Logs..."
if [ -f /var/log/auth.log ]; then
    tail -50 /var/log/auth.log 2>/dev/null | while read -r line; do
        TIME=$(echo "$line" | awk '{print $1" "$2" "$3}')
        DESC=$(echo "$line" | cut -d' ' -f4- | sed 's/"/\\"/g')
        echo "    {\"time\": \"$TIME\", \"event_id\": \"\", \"level\": \"info\", \"source\": \"auth\", \"description\": \"$DESC\"}," >> "$OUTPUT_FILE"
    done
elif [ -f /var/log/secure ]; then
    tail -50 /var/log/secure 2>/dev/null | while read -r line; do
        TIME=$(echo "$line" | awk '{print $1" "$2" "$3}')
        DESC=$(echo "$line" | cut -d' ' -f4- | sed 's/"/\\"/g')
        echo "    {\"time\": \"$TIME\", \"event_id\": \"\", \"level\": \"info\", \"source\": \"secure\", \"description\": \"$DESC\"}," >> "$OUTPUT_FILE"
    done
fi
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ]
}
EOFJSON

echo ""
echo "========================================"
echo "  Collection Complete!"
echo "  Output: $OUTPUT_FILE"
echo "========================================"