package service

import (
	"fmt"
	"strings"
)

func GenerateScript(template string, osType string, categories []string) (string, error) {
	allCategories := map[string]bool{
		"系统信息":   true,
		"用户账户":   true,
		"进程列表":   true,
		"网络连接":   true,
		"服务状态":   true,
		"启动项":     true,
		"计划任务":   true,
		"安全日志":   true,
		"注册表信息": true,
	}

	if len(categories) == 0 {
		for k := range allCategories {
			categories = append(categories, k)
		}
	}

	lines := strings.Split(template, "\n")
	var result []string
	inCategory := false
	includeCategory := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		for cat := range allCategories {
			if strings.Contains(trimmed, cat) && (strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "Write-Host") || strings.HasPrefix(trimmed, "echo")) {
				if inCategory {
					result = append(result, "")
				}
				inCategory = true
				includeCategory = contains(categories, cat)
				if includeCategory {
					result = append(result, line)
				}
				continue
			}
		}

		if inCategory {
			if trimmed == "" {
				inCategory = false
				continue
			}
			if includeCategory {
				result = append(result, line)
			}
			continue
		}

		if strings.HasPrefix(trimmed, "#") && strings.Contains(trimmed, "=====") {
			inCategory = true
			continue
		}

		result = append(result, line)
	}

	return strings.Join(result, "\n"), nil
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

func getDefaultScript(osType string) (string, error) {
	switch osType {
	case "windows":
		return windowsScript, nil
	case "linux":
		return linuxScript, nil
	case "macos":
		return macosScript, nil
	default:
		return "", fmt.Errorf("unsupported os type: %s", osType)
	}
}

const windowsScript = `# Windows Emergency Response Collection Script
# Generated by Emergency Response Platform
# ==========================================

$outputDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$outputFile = Join-Path $outputDir "emergency_collection_$(Get-Date -Format 'yyyyMMdd_HHmmss').json"
$result = @{}

Write-Host "========================================"
Write-Host "  Emergency Response Collection Script"
Write-Host "  Generated by Emergency Response Platform"
Write-Host "========================================"
Write-Host ""

# ========== 系统信息 ==========
Write-Host "[1/11] Collecting System Information..."
$sysInfo = @{
    hostname = [System.Net.Dns]::GetHostName()
    os_name = (Get-WmiObject Win32_OperatingSystem).Caption
    os_version = [System.Environment]::OSVersion.VersionString
    os_arch = (Get-WmiObject Win32_OperatingSystem).OSArchitecture
    uptime = ((Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime).ToString()
    current_user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    cpu_model = (Get-WmiObject Win32_Processor).Name
    cpu_cores = (Get-WmiObject Win32_ComputerSystem).NumberOfLogicalProcessors
    total_memory = [math]::Round((Get-WmiObject Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2).ToString() + " GB"
    disk_info = @(Get-WmiObject Win32_LogicalDisk -Filter "DriveType=3" | ForEach-Object {
        @{
            mount_point = $_.DeviceID
            total = [math]::Round($_.Size / 1GB, 2).ToString() + " GB"
            used = [math]::Round(($_.Size - $_.FreeSpace) / 1GB, 2).ToString() + " GB"
            available = [math]::Round($_.FreeSpace / 1GB, 2).ToString() + " GB"
        }
    })
}
$result.system_info = $sysInfo

# ========== 用户账户 ==========
Write-Host "[2/11] Collecting User Accounts..."
$users = @()
# Pre-fetch admin group members for efficient lookup
$adminMembers = @{}
$adminOutput = & net localgroup Administrators 2>$null
$inList = $false
foreach ($line in $adminOutput) {
    if ($line -match '^-+$') { $inList = !$inList; continue }
    if ($inList -and $line.Trim() -ne '' -and $line -notmatch '命令成功') {
        $adminMembers[$line.Trim()] = $true
    }
}
Get-WmiObject Win32_UserAccount -Filter "LocalAccount=True" | ForEach-Object {
    $isAdmin = $adminMembers.ContainsKey($_.Name)
    
    $users += @{
        username = $_.Name
        uid = $_.SID
        group = if ($isAdmin) { "Administrators" } else { "Users" }
        home_dir = ""
        shell = ""
        last_login = ""
        is_admin = $isAdmin
    }
}
$result.users = $users

# ========== 进程列表 ==========
Write-Host "[3/11] Collecting Process List..."
$processes = @()
Get-WmiObject Win32_Process | ForEach-Object {
    $procOwner = ""
    try {
        $owner = $_.GetOwner()
        if ($owner.ReturnValue -eq 0) { $procOwner = "$($owner.Domain)\$($owner.User)" }
    } catch {}
    $procName = $_.Name -replace '\.exe$',''
    $startTime = ""
    try { $startTime = $_.CreationDate.ToString("yyyy-MM-dd HH:mm:ss") } catch {}
    $cmdLine = if ($_.CommandLine) { $_.CommandLine } else { "" }
    $processes += @{
        pid = $_.ProcessId
        ppid = $_.ParentProcessId
        name = $procName
        user = $procOwner
        cpu = ""
        memory = [math]::Round($_.WorkingSetSize / 1MB, 2).ToString() + " MB"
        start_time = $startTime
        cmd_line = $cmdLine
    }
}
$result.processes = $processes

# ========== 网络连接 ==========
Write-Host "[4/11] Collecting Network Connections..."
$netConns = @()
try {
    $connections = Get-NetTCPConnection -ErrorAction SilentlyContinue | Select-Object LocalAddress, LocalPort, RemoteAddress, RemotePort, State, OwningProcess
    foreach ($conn in $connections) {
        $procName = ""
        try { $procName = (Get-Process -Id $conn.OwningProcess -ErrorAction SilentlyContinue).ProcessName } catch {}
        $netConns += @{
            proto = "tcp"
            local_addr = $conn.LocalAddress
            local_port = $conn.LocalPort.ToString()
            remote_addr = $conn.RemoteAddress
            remote_port = $conn.RemotePort.ToString()
            state = $conn.State.ToString()
            pid = $conn.OwningProcess
            proc_name = $procName
        }
    }
} catch {}
$result.network_conns = $netConns

# ========== 服务状态 ==========
Write-Host "[5/11] Collecting Services..."
$services = @()
Get-Service | ForEach-Object {
    $services += @{
        name = $_.Name
        display = $_.DisplayName
        status = $_.Status.ToString()
        start_type = $_.StartType.ToString()
    }
}
$result.services = $services

# ========== 启动项 ==========
Write-Host "[6/11] Collecting Startup Items..."
$startupItems = @()
$regPaths = @(
    "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run",
    "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run",
    "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce",
    "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce"
)
foreach ($path in $regPaths) {
    try {
        $items = Get-ItemProperty -Path $path -ErrorAction SilentlyContinue
        if ($items) {
            $items.PSObject.Properties | Where-Object { $_.Name -notmatch "^PS" } | ForEach-Object {
                $startupItems += @{
                    name = $_.Name
                    command = $_.Value
                    location = $path
                    user = if ($path -match "HKCU") { "CurrentUser" } else { "LocalMachine" }
                }
            }
        }
    } catch {}
}
$result.startup_items = $startupItems

# ========== 计划任务 ==========
Write-Host "[7/11] Collecting Scheduled Tasks..."
$scheduledTasks = @()
try {
    Get-ScheduledTask | ForEach-Object {
        $triggerStr = ""
        try {
            if ($_.Triggers) {
                $triggerDates = @($_.Triggers | ForEach-Object { $_.StartBoundary } | Where-Object { $_ })
                $triggerStr = ($triggerDates | Select-Object -First 3) -join "; "
            }
        } catch {}
        $actionStr = ""
        try {
            if ($_.Actions) {
                $actionStr = ($_.Actions | ForEach-Object { "$($_.Execute) $($_.Arguments)".Trim() }) -join "; "
            }
        } catch {}
        $scheduledTasks += @{
            name = $_.TaskName
            command = $actionStr
            schedule = $triggerStr
            user = if ($_.Principal) { $_.Principal.UserId } else { "" }
        }
    }
} catch {}
$result.scheduled_tasks = $scheduledTasks

# ========== 安全日志 ==========
Write-Host "[8/11] Collecting Security Logs..."
$securityLogs = @()
try {
    Get-WinEvent -LogName Security -MaxEvents 100 -ErrorAction SilentlyContinue | ForEach-Object {
        $securityLogs += @{
            time = $_.TimeCreated.ToString("yyyy-MM-dd HH:mm:ss")
            event_id = $_.Id.ToString()
            level = $_.LevelDisplayName
            source = $_.ProviderName
            description = $_.Message.Substring(0, [Math]::Min(500, $_.Message.Length))
        }
    }
} catch {}
$result.security_logs = $securityLogs

# ========== 注册表信息 - 隐藏账户 ==========
Write-Host "[9/11] Collecting Registry - Hidden Accounts..."
$regHiddenAccounts = @()
try {
    $samOut = & reg query "HKLM\SAM\SAM\Domains\Account\Users\Names" 2>$null
    if ($samOut) {
        $samLines = $samOut -split "` + "`" + `n" | Where-Object { $_ -match "HKEY_LOCAL_MACHINE" }
        foreach ($samLine in $samLines) {
            if ($samLine -match "\\Names\\(.+)$") {
                $regName = $matches[1].Trim()
                $regHiddenAccounts += @{
                    source = "SAM"
                    key = "HKLM\SAM\SAM\Domains\Account\Users\Names"
                    name = $regName
                    value = "(hidden via SAM)"
                    risk = "high"
                    note = "SAM registry account - may not appear in net user or WMI"
                }
            }
        }
    }
    $profileList = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\ProfileList\*" -ErrorAction SilentlyContinue
    if ($profileList) {
        $knownUsers = @{}
        Get-WmiObject Win32_UserAccount -Filter "LocalAccount=True" | ForEach-Object { $knownUsers[$_.Name] = $true }
        foreach ($profile in $profileList) {
            $profilePath = $profile.ProfileImagePath
            if ($profilePath) {
                $profileUser = Split-Path -Leaf $profilePath
                if ($profileUser -and $profileUser -notmatch "^(systemprofile|LocalService|NetworkService|Administrator|Default|Public)$" -and -not $knownUsers[$profileUser]) {
                    $regHiddenAccounts += @{
                        source = "ProfileList"
                        key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\ProfileList"
                        name = $profileUser
                        value = $profilePath
                        risk = "medium"
                        note = "Profile directory exists but user not in WMI"
                    }
                }
            }
        }
    }
    $specialAccounts = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList" -ErrorAction SilentlyContinue
    if ($specialAccounts) {
        $specialAccounts.PSObject.Properties | Where-Object { $_.Name -notmatch "^PS" } | ForEach-Object {
            if ($_.Value -eq 0) {
                $regHiddenAccounts += @{
                    source = "SpecialAccounts"
                    key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList"
                    name = $_.Name
                    value = "Hidden (DWORD=0)"
                    risk = "high"
                    note = "Account explicitly hidden from login screen"
                }
            }
        }
    }
} catch {}
$result.reg_hidden_accounts = $regHiddenAccounts

# ========== 注册表信息 - 计划任务路径 ==========
Write-Host "[10/11] Collecting Registry - Scheduled Task Paths..."
$regTaskPaths = @()
try {
    $taskCache = Get-ChildItem "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks" -ErrorAction SilentlyContinue
    if ($taskCache) {
        foreach ($taskGuid in $taskCache) {
            $guidName = Split-Path -Leaf $taskGuid.PSPath
            $taskProps = Get-ItemProperty $taskGuid.PSPath -ErrorAction SilentlyContinue
            if ($taskProps -and $taskProps.Path) {
                $taskPath = $taskProps.Path
                $taskActions = ""
                $taskUri = $taskProps.URI
                try {
                    $schTask = Get-ScheduledTask -TaskPath (Split-Path -Parent $taskPath) -TaskName (Split-Path -Leaf $taskPath) -ErrorAction SilentlyContinue
                    if ($schTask) {
                        $taskActions = ($schTask.Actions | ForEach-Object { $_.Execute + " " + $_.Arguments }) -join "; "
                    }
                } catch {}
                if ($taskPath) {
                    $regTaskPaths += @{
                        guid = $guidName
                        path = $taskPath
                        uri = if ($taskUri) { $taskUri } else { "" }
                        actions = $taskActions
                    }
                }
            }
        }
    }
} catch {}
$result.reg_task_paths = $regTaskPaths

# ========== 注册表信息 - 安全关键项 ==========
Write-Host "[11/11] Collecting Registry - Security Keys..."
$regSecurityKeys = @()
try {
    $winlogon = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" -ErrorAction SilentlyContinue
    if ($winlogon) {
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Shell"
            value = if ($winlogon.Shell) { $winlogon.Shell } else { "(default: explorer.exe)" }
            risk = if ($winlogon.Shell -and $winlogon.Shell -ne "explorer.exe") { "high" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Userinit"
            value = if ($winlogon.Userinit) { $winlogon.Userinit } else { "(default: userinit.exe)" }
            risk = if ($winlogon.Userinit -and $winlogon.Userinit -notmatch "userinit\.exe") { "high" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Notify"
            value = if ($winlogon.Notify) { $winlogon.Notify } else { "(not set)" }
            risk = if ($winlogon.Notify) { "medium" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Taskman"
            value = if ($winlogon.Taskman) { $winlogon.Taskman } else { "(not set)" }
            risk = if ($winlogon.Taskman) { "high" } else { "info" }
        }
    }
} catch {}
try {
    $ifeo = Get-ChildItem "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options" -ErrorAction SilentlyContinue
    if ($ifeo) {
        foreach ($entry in $ifeo) {
            $props = Get-ItemProperty $entry.PSPath -ErrorAction SilentlyContinue
            if ($props -and $props.Debugger) {
                $regSecurityKeys += @{
                    category = "IFEO"
                    key = $entry.PSPath -replace "Microsoft.PowerShell.Core\\Registry::", ""
                    name = (Split-Path -Leaf $entry.PSPath)
                    value = "Debugger: $($props.Debugger)"
                    risk = "high"
                }
            }
        }
    }
} catch {}
try {
    $appInit = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Windows" -ErrorAction SilentlyContinue
    if ($appInit) {
        $regSecurityKeys += @{
            category = "AppInit"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Windows"
            name = "AppInit_DLLs"
            value = if ($appInit.AppInit_DLLs) { $appInit.AppInit_DLLs } else { "(not set)" }
            risk = if ($appInit.AppInit_DLLs) { "high" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "AppInit"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Windows"
            name = "LoadAppInit_DLLs"
            value = if ($appInit.LoadAppInit_DLLs) { "$($appInit.LoadAppInit_DLLs)" } else { "(not set)" }
            risk = if ($appInit.LoadAppInit_DLLs -and $appInit.LoadAppInit_DLLs -ne 0) { "medium" } else { "info" }
        }
    }
} catch {}
try {
    $lsa = Get-ItemProperty "HKLM:\System\CurrentControlSet\Control\Lsa" -ErrorAction SilentlyContinue
    if ($lsa) {
        $regSecurityKeys += @{
            category = "LSA"
            key = "HKLM\System\CurrentControlSet\Control\Lsa"
            name = "Security Packages"
            value = if ($lsa."Security Packages") { [string]($lsa."Security Packages") } else { "(not set)" }
            risk = "info"
        }
        $regSecurityKeys += @{
            category = "LSA"
            key = "HKLM\System\CurrentControlSet\Control\Lsa"
            name = "Authentication Packages"
            value = if ($lsa."Authentication Packages") { [string]($lsa."Authentication Packages") } else { "(not set)" }
            risk = if ($lsa."Authentication Packages") { "medium" } else { "info" }
        }
    }
} catch {}
try {
    $winlogon2 = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" -ErrorAction SilentlyContinue
    if ($winlogon2 -and $winlogon2.GinaDLL) {
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "GinaDLL"
            value = $winlogon2.GinaDLL
            risk = "high"
        }
    }
} catch {}
$result.reg_security_keys = $regSecurityKeys

# Save results (no BOM for cross-platform compatibility)
$jsonOutput = $result | ConvertTo-Json -Depth 5
[System.IO.File]::WriteAllText($outputFile, $jsonOutput, [System.Text.UTF8Encoding]::new($false))
Write-Host ""
Write-Host "========================================"
Write-Host "  Collection Complete!"
Write-Host "  Output: $outputFile"
Write-Host "========================================"
`

const linuxScript = `#!/bin/bash
# Linux Emergency Response Collection Script
# Generated by Emergency Response Platform
# ==========================================

OUTPUT_DIR="$(cd "$(dirname "$0")" && pwd)"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="$OUTPUT_DIR/emergency_collection_${TIMESTAMP}.json"

echo "========================================"
echo "  Emergency Response Collection Script"
echo "  Generated by Emergency Response Platform"
echo "========================================"
echo ""

echo "[1/8] Collecting System Information..."
HOSTNAME=$(hostname)
OS_NAME=$(cat /etc/os-release 2>/dev/null | grep "^PRETTY_NAME" | cut -d'"' -f2)
OS_VERSION=$(uname -r)
OS_ARCH=$(uname -m)
UPTIME=$(uptime -p 2>/dev/null | sed 's/up //')
CURRENT_USER=$(whoami)
CPU_MODEL=$(grep "model name" /proc/cpuinfo 2>/dev/null | head -1 | cut -d':' -f2 | xargs)
CPU_CORES=$(nproc 2>/dev/null)
TOTAL_MEM=$(free -h 2>/dev/null | awk '/^Mem:/{print $2}')

cat > "$OUTPUT_FILE" << EOFJSON
{
  "system_info": {
    "hostname": "$HOSTNAME",
    "os_name": "$OS_NAME",
    "os_version": "$OS_VERSION",
    "os_arch": "$OS_ARCH",
    "kernel_version": "$OS_VERSION",
    "uptime": "$UPTIME",
    "current_user": "$CURRENT_USER",
    "cpu_model": "$CPU_MODEL",
    "cpu_cores": $CPU_CORES,
    "total_memory": "$TOTAL_MEM",
    "disk_info": [
EOFJSON

df -h 2>/dev/null | grep -vE '^Filesystem|tmpfs|devtmpfs' | while read -r line; do
    MOUNT=$(echo "$line" | awk '{print $6}')
    TOTAL=$(echo "$line" | awk '{print $2}')
    USED=$(echo "$line" | awk '{print $3}')
    AVAIL=$(echo "$line" | awk '{print $4}')
    echo "      {\"mount_point\": \"$MOUNT\", \"total\": \"$TOTAL\", \"used\": \"$USED\", \"available\": \"$AVAIL\"}," >> "$OUTPUT_FILE"
done

sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
    ]
  },
  "users": [
EOFJSON

echo "[2/8] Collecting User Accounts..."
while IFS=: read -r username _ uid gid _ home shell; do
    if [ "$uid" -ge 1000 ] 2>/dev/null || [ "$username" = "root" ]; then
        GROUP=$(id -gn "$username" 2>/dev/null || echo "")
        LAST_LOGIN=$(lastlog -u "$username" 2>/dev/null | tail -1 | awk '{print $NF}')
        IS_ADMIN="false"
        if [ "$username" = "root" ]; then IS_ADMIN="true"; fi
        if id -nG "$username" 2>/dev/null | grep -qw "sudo"; then IS_ADMIN="true"; fi
        echo "    {\"username\": \"$username\", \"uid\": \"$uid\", \"group\": \"$GROUP\", \"home_dir\": \"$home\", \"shell\": \"$shell\", \"last_login\": \"$LAST_LOGIN\", \"is_admin\": $IS_ADMIN}," >> "$OUTPUT_FILE"
    fi
done < /etc/passwd
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "processes": [
EOFJSON

echo "[3/8] Collecting Process List..."
ps aux --no-headers 2>/dev/null | while read -r user pid cpu mem _ _ _ _ _ _ cmd; do
    echo "    {\"pid\": $pid, \"ppid\": 0, \"name\": \"$(basename "$cmd" | cut -d' ' -f1)\", \"user\": \"$user\", \"cpu\": \"$cpu\", \"memory\": \"$mem\", \"start_time\": \"\", \"cmd_line\": \"$(echo "$cmd" | sed 's/"/\\"/g')\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "network_conns": [
EOFJSON

echo "[4/8] Collecting Network Connections..."
ss -tunap 2>/dev/null | tail -n +2 | while read -r proto recv send local remote state rest; do
    LOCAL_ADDR=$(echo "$local" | sed 's/:/ /g' | awk '{print $1}')
    LOCAL_PORT=$(echo "$local" | sed 's/:/ /g' | awk '{print $2}')
    REMOTE_ADDR=$(echo "$remote" | sed 's/:/ /g' | awk '{print $1}')
    REMOTE_PORT=$(echo "$remote" | sed 's/:/ /g' | awk '{print $2}')
    PID=$(echo "$rest" | grep -oP 'pid=\K[0-9]+' || echo "0")
    PROC_NAME=$(echo "$rest" | grep -oP 'users:\(\("\K[^"]+' || echo "")
    echo "    {\"proto\": \"$proto\", \"local_addr\": \"$LOCAL_ADDR\", \"local_port\": \"$LOCAL_PORT\", \"remote_addr\": \"$REMOTE_ADDR\", \"remote_port\": \"$REMOTE_PORT\", \"state\": \"$state\", \"pid\": $PID, \"proc_name\": \"$PROC_NAME\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "services": [
EOFJSON

echo "[5/8] Collecting Services..."
if command -v systemctl &>/dev/null; then
    systemctl list-units --type=service --all --no-pager 2>/dev/null | grep "\.service" | while read -r unit load active sub desc; do
        NAME=$(echo "$unit" | sed 's/\.service//')
        echo "    {\"name\": \"$NAME\", \"display\": \"$desc\", \"status\": \"$active\", \"start_type\": \"$sub\"}," >> "$OUTPUT_FILE"
    done
fi
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "startup_items": [
EOFJSON

echo "[6/8] Collecting Startup Items..."
for f in /etc/rc.local /etc/init.d/* /etc/systemd/system/*.service; do
    if [ -f "$f" ]; then
        BASENAME=$(basename "$f")
        echo "    {\"name\": \"$BASENAME\", \"command\": \"$f\", \"location\": \"$(dirname "$f")\", \"user\": \"root\"}," >> "$OUTPUT_FILE"
    fi
done 2>/dev/null
crontab -l 2>/dev/null | grep -v "^#" | while read -r line; do
    [ -z "$line" ] && continue
    echo "    {\"name\": \"cron-$(echo "$line" | md5sum | cut -c1-8)\", \"command\": \"$line\", \"location\": \"crontab\", \"user\": \"$CURRENT_USER\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "scheduled_tasks": [
EOFJSON

echo "[7/8] Collecting Scheduled Tasks..."
crontab -l 2>/dev/null | grep -v "^#" | while read -r line; do
    [ -z "$line" ] && continue
    SCHEDULE=$(echo "$line" | awk '{print $1" "$2" "$3" "$4" "$5}')
    CMD=$(echo "$line" | awk '{for(i=6;i<=NF;i++) printf "%s ", $i; print ""}')
    echo "    {\"name\": \"cron-task\", \"command\": \"$CMD\", \"schedule\": \"$SCHEDULE\", \"user\": \"$CURRENT_USER\"}," >> "$OUTPUT_FILE"
done
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ],
  "security_logs": [
EOFJSON

echo "[8/8] Collecting Security Logs..."
if [ -f /var/log/auth.log ]; then
    tail -50 /var/log/auth.log 2>/dev/null | while read -r line; do
        TIME=$(echo "$line" | awk '{print $1" "$2" "$3}')
        DESC=$(echo "$line" | cut -d' ' -f4- | sed 's/"/\\"/g')
        echo "    {\"time\": \"$TIME\", \"event_id\": \"\", \"level\": \"info\", \"source\": \"auth\", \"description\": \"$DESC\"}," >> "$OUTPUT_FILE"
    done
elif [ -f /var/log/secure ]; then
    tail -50 /var/log/secure 2>/dev/null | while read -r line; do
        TIME=$(echo "$line" | awk '{print $1" "$2" "$3}')
        DESC=$(echo "$line" | cut -d' ' -f4- | sed 's/"/\\"/g')
        echo "    {\"time\": \"$TIME\", \"event_id\": \"\", \"level\": \"info\", \"source\": \"secure\", \"description\": \"$DESC\"}," >> "$OUTPUT_FILE"
    done
fi
sed -i '$ s/,$//' "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOFJSON
  ]
}
EOFJSON

echo ""
echo "========================================"
echo "  Collection Complete!"
echo "  Output: $OUTPUT_FILE"
echo "========================================"
`

const macosScript = `#!/bin/bash
# macOS Emergency Response Collection Script
# Generated by Emergency Response Platform
# ==========================================

OUTPUT_DIR="$(cd "$(dirname "$0")" && pwd)"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="$OUTPUT_DIR/emergency_collection_${TIMESTAMP}.json"

echo "========================================"
echo "  Emergency Response Collection Script"
echo "  Generated by Emergency Response Platform"
echo "========================================"
echo ""

echo "[1/8] Collecting System Information..."
HOSTNAME=$(hostname)
OS_NAME="macOS $(sw_vers -productVersion 2>/dev/null)"
OS_VERSION=$(sw_vers -buildVersion 2>/dev/null)
OS_ARCH=$(uname -m)
UPTIME=$(uptime | sed 's/.*up \([^,]*\),.*/\1/')
CURRENT_USER=$(whoami)
CPU_MODEL=$(sysctl -n machdep.cpu.brand_string 2>/dev/null)
CPU_CORES=$(sysctl -n hw.ncpu 2>/dev/null)
TOTAL_MEM=$(( $(sysctl -n hw.memsize 2>/dev/null) / 1024 / 1024 / 1024 ))" GB"

echo "{" > "$OUTPUT_FILE"
echo "  \"system_info\": {" >> "$OUTPUT_FILE"
echo "    \"hostname\": \"$HOSTNAME\"," >> "$OUTPUT_FILE"
echo "    \"os_name\": \"$OS_NAME\"," >> "$OUTPUT_FILE"
echo "    \"os_version\": \"$OS_VERSION\"," >> "$OUTPUT_FILE"
echo "    \"os_arch\": \"$OS_ARCH\"," >> "$OUTPUT_FILE"
echo "    \"kernel_version\": \"$(uname -r)\"," >> "$OUTPUT_FILE"
echo "    \"uptime\": \"$UPTIME\"," >> "$OUTPUT_FILE"
echo "    \"current_user\": \"$CURRENT_USER\"," >> "$OUTPUT_FILE"
echo "    \"cpu_model\": \"$CPU_MODEL\"," >> "$OUTPUT_FILE"
echo "    \"cpu_cores\": $CPU_CORES," >> "$OUTPUT_FILE"
echo "    \"total_memory\": \"$TOTAL_MEM\"," >> "$OUTPUT_FILE"
cat >> "$OUTPUT_FILE" << 'EOFJSON'
    "disk_info": [
EOFJSON
df -h 2>/dev/null | grep -vE '^Filesystem|map ' | while read -r line; do
    MOUNT=$(echo "$line" | awk '{print $NF}')
    TOTAL=$(echo "$line" | awk '{print $2}')
    USED=$(echo "$line" | awk '{print $3}')
    AVAIL=$(echo "$line" | awk '{print $4}')
    echo "      {\"mount_point\": \"$MOUNT\", \"total\": \"$TOTAL\", \"used\": \"$USED\", \"available\": \"$AVAIL\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "    ]" >> "$OUTPUT_FILE"
echo "  }," >> "$OUTPUT_FILE"

echo "[2/8] Collecting User Accounts..."
echo '  "users": [' >> "$OUTPUT_FILE"
dscl . -list /Users 2>/dev/null | grep -v "^_" | while read -r username; do
    UID_VAL=$(dscl . -read /Users/"$username" UniqueID 2>/dev/null | awk '{print $2}')
    if [ "$UID_VAL" -ge 500 ] 2>/dev/null || [ "$username" = "root" ]; then
        HOME_DIR=$(dscl . -read /Users/"$username" NFSHomeDirectory 2>/dev/null | awk '{print $2}')
        SHELL_VAL=$(dscl . -read /Users/"$username" UserShell 2>/dev/null | awk '{print $2}')
        IS_ADMIN="false"
        if groups "$username" 2>/dev/null | grep -qw "admin"; then IS_ADMIN="true"; fi
        if [ "$username" = "root" ]; then IS_ADMIN="true"; fi
        echo "    {\"username\": \"$username\", \"uid\": \"$UID_VAL\", \"group\": \"staff\", \"home_dir\": \"$HOME_DIR\", \"shell\": \"$SHELL_VAL\", \"last_login\": \"\", \"is_admin\": $IS_ADMIN}," >> "$OUTPUT_FILE"
    fi
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[3/8] Collecting Process List..."
echo '  "processes": [' >> "$OUTPUT_FILE"
ps aux 2>/dev/null | tail -n +2 | while read -r user pid cpu mem _ _ _ _ _ _ cmd; do
    echo "    {\"pid\": $pid, \"ppid\": 0, \"name\": \"$(basename "$cmd" | cut -d' ' -f1)\", \"user\": \"$user\", \"cpu\": \"$cpu\", \"memory\": \"$mem\", \"start_time\": \"\", \"cmd_line\": \"$(echo "$cmd" | sed 's/"/\\"/g')\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[4/8] Collecting Network Connections..."
echo '  "network_conns": [' >> "$OUTPUT_FILE"
lsof -i -nP 2>/dev/null | tail -n +2 | while read -r cmd pid _ _ _ proto _; do
    if echo "$proto" | grep -qE '(TCP|UDP)'; then
        CONN_INFO=$(echo "$proto" | awk -F'[()]' '{print $2}')
        LOCAL=$(echo "$CONN_INFO" | awk '{print $1}')
        REMOTE=$(echo "$CONN_INFO" | awk '{print $3}')
        LOCAL_ADDR=$(echo "$LOCAL" | cut -d':' -f1)
        LOCAL_PORT=$(echo "$LOCAL" | cut -d':' -f2)
        REMOTE_ADDR=$(echo "$REMOTE" | cut -d':' -f1)
        REMOTE_PORT=$(echo "$REMOTE" | cut -d':' -f2)
        PROTOTYPE=$(echo "$proto" | grep -oE 'TCP|UDP' | tr '[:upper:]' '[:lower:]')
        echo "    {\"proto\": \"$PROTOTYPE\", \"local_addr\": \"$LOCAL_ADDR\", \"local_port\": \"$LOCAL_PORT\", \"remote_addr\": \"$REMOTE_ADDR\", \"remote_port\": \"$REMOTE_PORT\", \"state\": \"\", \"pid\": $pid, \"proc_name\": \"$cmd\"}," >> "$OUTPUT_FILE"
    fi
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[5/8] Collecting Services..."
echo '  "services": [' >> "$OUTPUT_FILE"
launchctl list 2>/dev/null | tail -n +2 | while read -r pid status name; do
    echo "    {\"name\": \"$name\", \"display\": \"$name\", \"status\": \"$status\", \"start_type\": \"launchd\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[6/8] Collecting Startup Items..."
echo '  "startup_items": [' >> "$OUTPUT_FILE"
for dir in /Library/LaunchDaemons /Library/LaunchAgents ~/Library/LaunchAgents; do
    if [ -d "$dir" ]; then
        for f in "$dir"/*.plist; do
            [ -f "$f" ] || continue
            BASENAME=$(basename "$f")
            echo "    {\"name\": \"$BASENAME\", \"command\": \"$f\", \"location\": \"$dir\", \"user\": \"\"}," >> "$OUTPUT_FILE"
        done
    fi
done 2>/dev/null
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[7/8] Collecting Scheduled Tasks..."
echo '  "scheduled_tasks": [' >> "$OUTPUT_FILE"
crontab -l 2>/dev/null | grep -v "^#" | while read -r line; do
    [ -z "$line" ] && continue
    SCHEDULE=$(echo "$line" | awk '{print $1" "$2" "$3" "$4" "$5}')
    CMD=$(echo "$line" | awk '{for(i=6;i<=NF;i++) printf "%s ", $i; print ""}')
    echo "    {\"name\": \"cron-task\", \"command\": \"$CMD\", \"schedule\": \"$SCHEDULE\", \"user\": \"$CURRENT_USER\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[8/8] Collecting Security Logs..."
echo '  "security_logs": [' >> "$OUTPUT_FILE"
log show --predicate 'eventMessage contains "error" OR eventMessage contains "failed"' --last 1h --style compact 2>/dev/null | head -30 | while read -r line; do
    TIME=$(echo "$line" | awk '{print $1" "$2}')
    DESC=$(echo "$line" | cut -d' ' -f3- | sed 's/"/\\"/g')
    echo "    {\"time\": \"$TIME\", \"event_id\": \"\", \"level\": \"info\", \"source\": \"system\", \"description\": \"$DESC\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]" >> "$OUTPUT_FILE"

echo "}" >> "$OUTPUT_FILE"
echo ""
echo "========================================"
echo "  Collection Complete!"
echo "  Output: $OUTPUT_FILE"
echo "========================================"
`