#!/bin/bash
# macOS Emergency Response Collection Script
# Generated by Emergency Response Platform
# ==========================================

OUTPUT_DIR="$(cd "$(dirname "$0")" && pwd)"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="$OUTPUT_DIR/emergency_collection_${TIMESTAMP}.json"

echo "========================================"
echo "  Emergency Response Collection Script"
echo "  Generated by Emergency Response Platform"
echo "========================================"
echo ""

echo "[1/8] Collecting System Information..."
HOSTNAME=$(hostname)
OS_NAME="macOS $(sw_vers -productVersion 2>/dev/null)"
OS_VERSION=$(sw_vers -buildVersion 2>/dev/null)
OS_ARCH=$(uname -m)
UPTIME=$(uptime | sed 's/.*up \([^,]*\),.*/\1/')
CURRENT_USER=$(whoami)
CPU_MODEL=$(sysctl -n machdep.cpu.brand_string 2>/dev/null)
CPU_CORES=$(sysctl -n hw.ncpu 2>/dev/null)
TOTAL_MEM=$(( $(sysctl -n hw.memsize 2>/dev/null) / 1024 / 1024 / 1024 ))" GB"

echo "{" > "$OUTPUT_FILE"
echo "  \"system_info\": {" >> "$OUTPUT_FILE"
echo "    \"hostname\": \"$HOSTNAME\"," >> "$OUTPUT_FILE"
echo "    \"os_name\": \"$OS_NAME\"," >> "$OUTPUT_FILE"
echo "    \"os_version\": \"$OS_VERSION\"," >> "$OUTPUT_FILE"
echo "    \"os_arch\": \"$OS_ARCH\"," >> "$OUTPUT_FILE"
echo "    \"kernel_version\": \"$(uname -r)\"," >> "$OUTPUT_FILE"
echo "    \"uptime\": \"$UPTIME\"," >> "$OUTPUT_FILE"
echo "    \"current_user\": \"$CURRENT_USER\"," >> "$OUTPUT_FILE"
echo "    \"cpu_model\": \"$CPU_MODEL\"," >> "$OUTPUT_FILE"
echo "    \"cpu_cores\": $CPU_CORES," >> "$OUTPUT_FILE"
echo "    \"total_memory\": \"$TOTAL_MEM\"," >> "$OUTPUT_FILE"
cat >> "$OUTPUT_FILE" << 'EOFJSON'
    "disk_info": [
EOFJSON
df -h 2>/dev/null | grep -vE '^Filesystem|map ' | while read -r line; do
    MOUNT=$(echo "$line" | awk '{print $NF}')
    TOTAL=$(echo "$line" | awk '{print $2}')
    USED=$(echo "$line" | awk '{print $3}')
    AVAIL=$(echo "$line" | awk '{print $4}')
    echo "      {\"mount_point\": \"$MOUNT\", \"total\": \"$TOTAL\", \"used\": \"$USED\", \"available\": \"$AVAIL\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "    ]" >> "$OUTPUT_FILE"
echo "  }," >> "$OUTPUT_FILE"

echo "[2/8] Collecting User Accounts..."
echo '  "users": [' >> "$OUTPUT_FILE"
dscl . -list /Users 2>/dev/null | grep -v "^_" | while read -r username; do
    UID_VAL=$(dscl . -read /Users/"$username" UniqueID 2>/dev/null | awk '{print $2}')
    if [ "$UID_VAL" -ge 500 ] 2>/dev/null || [ "$username" = "root" ]; then
        HOME_DIR=$(dscl . -read /Users/"$username" NFSHomeDirectory 2>/dev/null | awk '{print $2}')
        SHELL_VAL=$(dscl . -read /Users/"$username" UserShell 2>/dev/null | awk '{print $2}')
        IS_ADMIN="false"
        if groups "$username" 2>/dev/null | grep -qw "admin"; then IS_ADMIN="true"; fi
        if [ "$username" = "root" ]; then IS_ADMIN="true"; fi
        echo "    {\"username\": \"$username\", \"uid\": \"$UID_VAL\", \"group\": \"staff\", \"home_dir\": \"$HOME_DIR\", \"shell\": \"$SHELL_VAL\", \"last_login\": \"\", \"is_admin\": $IS_ADMIN}," >> "$OUTPUT_FILE"
    fi
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[3/8] Collecting Process List..."
echo '  "processes": [' >> "$OUTPUT_FILE"
ps aux 2>/dev/null | tail -n +2 | while read -r user pid cpu mem _ _ _ _ _ _ cmd; do
    echo "    {\"pid\": $pid, \"ppid\": 0, \"name\": \"$(basename "$cmd" | cut -d' ' -f1)\", \"user\": \"$user\", \"cpu\": \"$cpu\", \"memory\": \"$mem\", \"start_time\": \"\", \"cmd_line\": \"$(echo "$cmd" | sed 's/"/\\"/g')\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[4/8] Collecting Network Connections..."
echo '  "network_conns": [' >> "$OUTPUT_FILE"
lsof -i -nP 2>/dev/null | tail -n +2 | while read -r cmd pid _ _ _ proto _; do
    if echo "$proto" | grep -qE '(TCP|UDP)'; then
        CONN_INFO=$(echo "$proto" | awk -F'[()]' '{print $2}')
        LOCAL=$(echo "$CONN_INFO" | awk '{print $1}')
        REMOTE=$(echo "$CONN_INFO" | awk '{print $3}')
        LOCAL_ADDR=$(echo "$LOCAL" | cut -d':' -f1)
        LOCAL_PORT=$(echo "$LOCAL" | cut -d':' -f2)
        REMOTE_ADDR=$(echo "$REMOTE" | cut -d':' -f1)
        REMOTE_PORT=$(echo "$REMOTE" | cut -d':' -f2)
        PROTOTYPE=$(echo "$proto" | grep -oE 'TCP|UDP' | tr '[:upper:]' '[:lower:]')
        echo "    {\"proto\": \"$PROTOTYPE\", \"local_addr\": \"$LOCAL_ADDR\", \"local_port\": \"$LOCAL_PORT\", \"remote_addr\": \"$REMOTE_ADDR\", \"remote_port\": \"$REMOTE_PORT\", \"state\": \"\", \"pid\": $pid, \"proc_name\": \"$cmd\"}," >> "$OUTPUT_FILE"
    fi
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[5/8] Collecting Services..."
echo '  "services": [' >> "$OUTPUT_FILE"
launchctl list 2>/dev/null | tail -n +2 | while read -r pid status name; do
    echo "    {\"name\": \"$name\", \"display\": \"$name\", \"status\": \"$status\", \"start_type\": \"launchd\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[6/8] Collecting Startup Items..."
echo '  "startup_items": [' >> "$OUTPUT_FILE"
for dir in /Library/LaunchDaemons /Library/LaunchAgents ~/Library/LaunchAgents; do
    if [ -d "$dir" ]; then
        for f in "$dir"/*.plist; do
            [ -f "$f" ] || continue
            BASENAME=$(basename "$f")
            echo "    {\"name\": \"$BASENAME\", \"command\": \"$f\", \"location\": \"$dir\", \"user\": \"\"}," >> "$OUTPUT_FILE"
        done
    fi
done 2>/dev/null
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[7/8] Collecting Scheduled Tasks..."
echo '  "scheduled_tasks": [' >> "$OUTPUT_FILE"
crontab -l 2>/dev/null | grep -v "^#" | while read -r line; do
    [ -z "$line" ] && continue
    SCHEDULE=$(echo "$line" | awk '{print $1" "$2" "$3" "$4" "$5}')
    CMD=$(echo "$line" | awk '{for(i=6;i<=NF;i++) printf "%s ", $i; print ""}')
    echo "    {\"name\": \"cron-task\", \"command\": \"$CMD\", \"schedule\": \"$SCHEDULE\", \"user\": \"$CURRENT_USER\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]," >> "$OUTPUT_FILE"

echo "[8/8] Collecting Security Logs..."
echo '  "security_logs": [' >> "$OUTPUT_FILE"
log show --predicate 'eventMessage contains "error" OR eventMessage contains "failed"' --last 1h --style compact 2>/dev/null | head -30 | while read -r line; do
    TIME=$(echo "$line" | awk '{print $1" "$2}')
    DESC=$(echo "$line" | cut -d' ' -f3- | sed 's/"/\\"/g')
    echo "    {\"time\": \"$TIME\", \"event_id\": \"\", \"level\": \"info\", \"source\": \"system\", \"description\": \"$DESC\"}," >> "$OUTPUT_FILE"
done
sed -i '' '$ s/,$//' "$OUTPUT_FILE" 2>/dev/null || sed -i '$ s/,$//' "$OUTPUT_FILE"
echo "  ]" >> "$OUTPUT_FILE"

echo "}" >> "$OUTPUT_FILE"
echo ""
echo "========================================"
echo "  Collection Complete!"
echo "  Output: $OUTPUT_FILE"
echo "========================================"