# Windows Emergency Response Collection Script
# Generated by Emergency Response Platform
# ==========================================

$outputDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$outputFile = Join-Path $outputDir "emergency_collection_$(Get-Date -Format 'yyyyMMdd_HHmmss').json"
$result = @{}

Write-Host "========================================"
Write-Host "  Emergency Response Collection Script"
Write-Host "  Generated by Emergency Response Platform"
Write-Host "========================================"
Write-Host ""

# ========== 系统信息 ==========
Write-Host "[1/11] Collecting System Information..."
$sysInfo = @{
    hostname = [System.Net.Dns]::GetHostName()
    os_name = (Get-WmiObject Win32_OperatingSystem).Caption
    os_version = [System.Environment]::OSVersion.VersionString
    os_arch = (Get-WmiObject Win32_OperatingSystem).OSArchitecture
    uptime = ((Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime).ToString()
    current_user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    cpu_model = (Get-WmiObject Win32_Processor).Name
    cpu_cores = (Get-WmiObject Win32_ComputerSystem).NumberOfLogicalProcessors
    total_memory = [math]::Round((Get-WmiObject Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2).ToString() + " GB"
    disk_info = @(Get-WmiObject Win32_LogicalDisk -Filter "DriveType=3" | ForEach-Object {
        @{
            mount_point = $_.DeviceID
            total = [math]::Round($_.Size / 1GB, 2).ToString() + " GB"
            used = [math]::Round(($_.Size - $_.FreeSpace) / 1GB, 2).ToString() + " GB"
            available = [math]::Round($_.FreeSpace / 1GB, 2).ToString() + " GB"
        }
    })
}
$result.system_info = $sysInfo

# ========== 用户账户 ==========
Write-Host "[2/11] Collecting User Accounts..."
$users = @()
# Pre-fetch admin group members for efficient lookup
$adminMembers = @{}
$adminOutput = & net localgroup Administrators 2>$null
$inList = $false
foreach ($line in $adminOutput) {
    if ($line -match '^-+$') { $inList = !$inList; continue }
    if ($inList -and $line.Trim() -ne '' -and $line -notmatch '命令成功') {
        $adminMembers[$line.Trim()] = $true
    }
}
Get-WmiObject Win32_UserAccount -Filter "LocalAccount=True" | ForEach-Object {
    $isAdmin = $adminMembers.ContainsKey($_.Name)
    
    $users += @{
        username = $_.Name
        uid = $_.SID
        group = if ($isAdmin) { "Administrators" } else { "Users" }
        home_dir = ""
        shell = ""
        last_login = ""
        is_admin = $isAdmin
    }
}
$result.users = $users

# ========== 进程列表 ==========
Write-Host "[3/11] Collecting Process List..."
$processes = @()
Get-WmiObject Win32_Process | ForEach-Object {
    $procOwner = ""
    try {
        $owner = $_.GetOwner()
        if ($owner.ReturnValue -eq 0) { $procOwner = "$($owner.Domain)\$($owner.User)" }
    } catch {}
    $procName = $_.Name -replace '\.exe$',''
    $startTime = ""
    try { $startTime = $_.CreationDate.ToString("yyyy-MM-dd HH:mm:ss") } catch {}
    $cmdLine = if ($_.CommandLine) { $_.CommandLine } else { "" }
    $processes += @{
        pid = $_.ProcessId
        ppid = $_.ParentProcessId
        name = $procName
        user = $procOwner
        cpu = ""
        memory = [math]::Round($_.WorkingSetSize / 1MB, 2).ToString() + " MB"
        start_time = $startTime
        cmd_line = $cmdLine
    }
}
$result.processes = $processes

# ========== 网络连接 ==========
Write-Host "[4/11] Collecting Network Connections..."
$netConns = @()
try {
    $connections = Get-NetTCPConnection -ErrorAction SilentlyContinue | Select-Object LocalAddress, LocalPort, RemoteAddress, RemotePort, State, OwningProcess
    foreach ($conn in $connections) {
        $procName = ""
        try { $procName = (Get-Process -Id $conn.OwningProcess -ErrorAction SilentlyContinue).ProcessName } catch {}
        $netConns += @{
            proto = "tcp"
            local_addr = $conn.LocalAddress
            local_port = $conn.LocalPort.ToString()
            remote_addr = $conn.RemoteAddress
            remote_port = $conn.RemotePort.ToString()
            state = $conn.State.ToString()
            pid = $conn.OwningProcess
            proc_name = $procName
        }
    }
} catch {}
$result.network_conns = $netConns

# ========== 服务状态 ==========
Write-Host "[5/11] Collecting Services..."
$services = @()
Get-Service | ForEach-Object {
    $services += @{
        name = $_.Name
        display = $_.DisplayName
        status = $_.Status.ToString()
        start_type = $_.StartType.ToString()
    }
}
$result.services = $services

# ========== 启动项 ==========
Write-Host "[6/11] Collecting Startup Items..."
$startupItems = @()
$regPaths = @(
    "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run",
    "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run",
    "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce",
    "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce"
)
foreach ($path in $regPaths) {
    try {
        $items = Get-ItemProperty -Path $path -ErrorAction SilentlyContinue
        if ($items) {
            $items.PSObject.Properties | Where-Object { $_.Name -notmatch "^PS" } | ForEach-Object {
                $startupItems += @{
                    name = $_.Name
                    command = $_.Value
                    location = $path
                    user = if ($path -match "HKCU") { "CurrentUser" } else { "LocalMachine" }
                }
            }
        }
    } catch {}
}
$result.startup_items = $startupItems

# ========== 计划任务 ==========
Write-Host "[7/11] Collecting Scheduled Tasks..."
$scheduledTasks = @()
try {
    Get-ScheduledTask | ForEach-Object {
        $triggerStr = ""
        try {
            if ($_.Triggers) {
                $triggerDates = @($_.Triggers | ForEach-Object { $_.StartBoundary } | Where-Object { $_ })
                $triggerStr = ($triggerDates | Select-Object -First 3) -join "; "
            }
        } catch {}
        $actionStr = ""
        try {
            if ($_.Actions) {
                $actionStr = ($_.Actions | ForEach-Object { "$($_.Execute) $($_.Arguments)".Trim() }) -join "; "
            }
        } catch {}
        $scheduledTasks += @{
            name = $_.TaskName
            command = $actionStr
            schedule = $triggerStr
            user = if ($_.Principal) { $_.Principal.UserId } else { "" }
        }
    }
} catch {}
$result.scheduled_tasks = $scheduledTasks

# ========== 安全日志 ==========
Write-Host "[8/11] Collecting Security Logs..."
$securityLogs = @()
try {
    Get-WinEvent -LogName Security -MaxEvents 100 -ErrorAction SilentlyContinue | ForEach-Object {
        $securityLogs += @{
            time = $_.TimeCreated.ToString("yyyy-MM-dd HH:mm:ss")
            event_id = $_.Id.ToString()
            level = $_.LevelDisplayName
            source = $_.ProviderName
            description = $_.Message.Substring(0, [Math]::Min(500, $_.Message.Length))
        }
    }
} catch {}
$result.security_logs = $securityLogs

# ========== 注册表信息 - 隐藏账户 ==========
Write-Host "[9/11] Collecting Registry - Hidden Accounts..."
$regHiddenAccounts = @()
try {
    # Method 1: Check for HKLM\SAM\SAM\Domains\Account\Users\Names (requires SYSTEM)
    # Attempt to read SAM via reg.exe as alternative
    $samOut = & reg query "HKLM\SAM\SAM\Domains\Account\Users\Names" 2>$null
    if ($samOut) {
        $samLines = $samOut -split "`n" | Where-Object { $_ -match "HKEY_LOCAL_MACHINE" }
        foreach ($samLine in $samLines) {
            if ($samLine -match "\\Names\\(.+)$") {
                $regName = $matches[1].Trim()
                $regHiddenAccounts += @{
                    source = "SAM"
                    key = "HKLM\SAM\SAM\Domains\Account\Users\Names"
                    name = $regName
                    value = "(hidden via SAM)"
                    risk = "high"
                    note = "SAM registry account - may not appear in net user or WMI"
                }
            }
        }
    }
    
    # Method 2: ProfileList - find user profiles not matching known accounts
    $profileList = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\ProfileList\*" -ErrorAction SilentlyContinue
    if ($profileList) {
        $knownUsers = @{}
        Get-WmiObject Win32_UserAccount -Filter "LocalAccount=True" | ForEach-Object { $knownUsers[$_.Name] = $true }
        foreach ($profile in $profileList) {
            $profilePath = $profile.ProfileImagePath
            if ($profilePath) {
                $profileUser = Split-Path -Leaf $profilePath
                if ($profileUser -and $profileUser -notmatch "^(systemprofile|LocalService|NetworkService|Administrator|Default|Public)$" -and -not $knownUsers[$profileUser]) {
                    $regHiddenAccounts += @{
                        source = "ProfileList"
                        key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\ProfileList"
                        name = $profileUser
                        value = $profilePath
                        risk = "medium"
                        note = "Profile directory exists but user not listed in WMI - possible hidden account"
                    }
                }
            }
        }
    }
    
    # Method 3: Check SpecialAccounts key (explicitly hidden from login screen)
    $specialAccounts = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList" -ErrorAction SilentlyContinue
    if ($specialAccounts) {
        $specialAccounts.PSObject.Properties | Where-Object { $_.Name -notmatch "^PS" } | ForEach-Object {
            if ($_.Value -eq 0) {
                $regHiddenAccounts += @{
                    source = "SpecialAccounts"
                    key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList"
                    name = $_.Name
                    value = "Hidden from login (DWORD=0)"
                    risk = "high"
                    note = "Account explicitly hidden from Windows login screen"
                }
            }
        }
    }
} catch {}
$result.reg_hidden_accounts = $regHiddenAccounts

# ========== 注册表信息 - 计划任务路径 ==========
Write-Host "[10/11] Collecting Registry - Scheduled Task Paths..."
$regTaskPaths = @()
try {
    # Query TaskCache for detailed task paths that may differ from Get-ScheduledTask
    $taskCache = Get-ChildItem "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks" -ErrorAction SilentlyContinue
    if ($taskCache) {
        foreach ($taskGuid in $taskCache) {
            $guidName = Split-Path -Leaf $taskGuid.PSPath
            $taskProps = Get-ItemProperty $taskGuid.PSPath -ErrorAction SilentlyContinue
            if ($taskProps -and $taskProps.Path) {
                $taskPath = $taskProps.Path
                # Try to get the actual Actions from the task XML
                $taskActions = ""
                $taskUri = $taskProps.URI
                try {
                    $schTask = Get-ScheduledTask -TaskPath (Split-Path -Parent $taskPath) -TaskName (Split-Path -Leaf $taskPath) -ErrorAction SilentlyContinue
                    if ($schTask) {
                        $taskActions = ($schTask.Actions | ForEach-Object { $_.Execute + " " + $_.Arguments }) -join "; "
                    }
                } catch {}
                if ($taskPath -and $taskPath -ne "") {
                    $regTaskPaths += @{
                        guid = $guidName
                        path = $taskPath
                        uri = if ($taskUri) { $taskUri } else { "" }
                        actions = $taskActions
                    }
                }
            }
        }
    }
} catch {}
$result.reg_task_paths = $regTaskPaths

# ========== 注册表信息 - 安全关键项 ==========
Write-Host "[11/11] Collecting Registry - Security Keys..."
$regSecurityKeys = @()

# Winlogon Shell/Userinit (common persistence)
try {
    $winlogon = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" -ErrorAction SilentlyContinue
    if ($winlogon) {
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Shell"
            value = if ($winlogon.Shell) { $winlogon.Shell } else { "(default: explorer.exe)" }
            risk = if ($winlogon.Shell -and $winlogon.Shell -ne "explorer.exe") { "high" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Userinit"
            value = if ($winlogon.Userinit) { $winlogon.Userinit } else { "(default: userinit.exe)" }
            risk = if ($winlogon.Userinit -and $winlogon.Userinit -notmatch "userinit\.exe") { "high" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Notify"
            value = if ($winlogon.Notify) { $winlogon.Notify } else { "(not set)" }
            risk = if ($winlogon.Notify) { "medium" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "Taskman"
            value = if ($winlogon.Taskman) { $winlogon.Taskman } else { "(not set)" }
            risk = if ($winlogon.Taskman) { "high" } else { "info" }
        }
    }
} catch {}

# Image File Execution Options (debugger hijacking)
try {
    $ifeo = Get-ChildItem "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options" -ErrorAction SilentlyContinue
    if ($ifeo) {
        foreach ($entry in $ifeo) {
            $props = Get-ItemProperty $entry.PSPath -ErrorAction SilentlyContinue
            if ($props -and $props.Debugger) {
                $regSecurityKeys += @{
                    category = "IFEO"
                    key = $entry.PSPath -replace "Microsoft.PowerShell.Core\\Registry::", ""
                    name = (Split-Path -Leaf $entry.PSPath)
                    value = "Debugger: $($props.Debugger)"
                    risk = "high"
                }
            }
        }
    }
} catch {}

# AppInit_DLLs
try {
    $appInit = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Windows" -ErrorAction SilentlyContinue
    if ($appInit) {
        $regSecurityKeys += @{
            category = "AppInit"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Windows"
            name = "AppInit_DLLs"
            value = if ($appInit.AppInit_DLLs) { $appInit.AppInit_DLLs } else { "(not set)" }
            risk = if ($appInit.AppInit_DLLs) { "high" } else { "info" }
        }
        $regSecurityKeys += @{
            category = "AppInit"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Windows"
            name = "LoadAppInit_DLLs"
            value = if ($appInit.LoadAppInit_DLLs) { "$($appInit.LoadAppInit_DLLs)" } else { "(not set)" }
            risk = if ($appInit.LoadAppInit_DLLs -and $appInit.LoadAppInit_DLLs -ne 0) { "medium" } else { "info" }
        }
    }
} catch {}

# LSA Packages (can load arbitrary DLLs at boot)
try {
    $lsa = Get-ItemProperty "HKLM:\System\CurrentControlSet\Control\Lsa" -ErrorAction SilentlyContinue
    if ($lsa) {
        $regSecurityKeys += @{
            category = "LSA"
            key = "HKLM\System\CurrentControlSet\Control\Lsa"
            name = "Security Packages"
            value = if ($lsa."Security Packages") { [string]($lsa."Security Packages") } else { "(not set)" }
            risk = "info"
        }
        $regSecurityKeys += @{
            category = "LSA"
            key = "HKLM\System\CurrentControlSet\Control\Lsa"
            name = "Authentication Packages"
            value = if ($lsa."Authentication Packages") { [string]($lsa."Authentication Packages") } else { "(not set)" }
            risk = if ($lsa."Authentication Packages") { "medium" } else { "info" }
        }
    }
} catch {}

# Winlogon/GinaDLL (legacy credential hijacking)
try {
    $winlogon2 = Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" -ErrorAction SilentlyContinue
    if ($winlogon2 -and $winlogon2.GinaDLL) {
        $regSecurityKeys += @{
            category = "Winlogon"
            key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"
            name = "GinaDLL"
            value = $winlogon2.GinaDLL
            risk = "high"
        }
    }
} catch {}

# Scheduled Tasks - check for at jobs
$regSecurityKeys += @{
    category = "Persistence"
    key = "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache"
    name = "TaskCacheEntries"
    value = "$($regTaskPaths.Count) task entries in cache"
    risk = "info"
}

$result.reg_security_keys = $regSecurityKeys

# Save results (no BOM for cross-platform compatibility)
$jsonOutput = $result | ConvertTo-Json -Depth 5
[System.IO.File]::WriteAllText($outputFile, $jsonOutput, [System.Text.UTF8Encoding]::new($false))
Write-Host ""
Write-Host "========================================"
Write-Host "  Collection Complete!"
Write-Host "  Output: $outputFile"
Write-Host "========================================"